
package anmbaseservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ServiceInfoAnmLineeClasseSoap", targetNamespace = "http://m.anm.it/srv/")
public interface ServiceInfoAnmLineeClasseSoap {


    /**
     * 
     * @param linea
     * @return
     *     returns anmbaseservices.ArrayOfPosizioneVeicolo
     */
    @WebMethod(operationName = "CaricaPosizioneVeicolo", action = "http://m.anm.it/srv/CaricaPosizioneVeicolo")
    @WebResult(name = "CaricaPosizioneVeicoloResult", targetNamespace = "http://m.anm.it/srv/")
    @RequestWrapper(localName = "CaricaPosizioneVeicolo", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaPosizioneVeicolo")
    @ResponseWrapper(localName = "CaricaPosizioneVeicoloResponse", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaPosizioneVeicoloResponse")
    public ArrayOfPosizioneVeicolo caricaPosizioneVeicolo(
        @WebParam(name = "linea", targetNamespace = "http://m.anm.it/srv/")
        String linea);

    /**
     * 
     * @return
     *     returns anmbaseservices.ArrayOfLinea
     */
    @WebMethod(operationName = "CaricaElencoLinee", action = "http://m.anm.it/srv/CaricaElencoLinee")
    @WebResult(name = "CaricaElencoLineeResult", targetNamespace = "http://m.anm.it/srv/")
    @RequestWrapper(localName = "CaricaElencoLinee", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaElencoLinee")
    @ResponseWrapper(localName = "CaricaElencoLineeResponse", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaElencoLineeResponse")
    public ArrayOfLinea caricaElencoLinee();

    /**
     * 
     * @return
     *     returns anmbaseservices.ArrayOfComune
     */
    @WebMethod(operationName = "CaricaElencoComuni", action = "http://m.anm.it/srv/CaricaElencoComuni")
    @WebResult(name = "CaricaElencoComuniResult", targetNamespace = "http://m.anm.it/srv/")
    @RequestWrapper(localName = "CaricaElencoComuni", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaElencoComuni")
    @ResponseWrapper(localName = "CaricaElencoComuniResponse", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaElencoComuniResponse")
    public ArrayOfComune caricaElencoComuni();

    /**
     * 
     * @return
     *     returns anmbaseservices.ArrayOfPalina
     */
    @WebMethod(operationName = "CaricaElencoPaline", action = "http://m.anm.it/srv/CaricaElencoPaline")
    @WebResult(name = "CaricaElencoPalineResult", targetNamespace = "http://m.anm.it/srv/")
    @RequestWrapper(localName = "CaricaElencoPaline", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaElencoPaline")
    @ResponseWrapper(localName = "CaricaElencoPalineResponse", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaElencoPalineResponse")
    public ArrayOfPalina caricaElencoPaline();

    /**
     * 
     * @param palina
     * @return
     *     returns anmbaseservices.ArrayOfPrevisione
     */
    @WebMethod(operationName = "CaricaPrevisioni", action = "http://m.anm.it/srv/CaricaPrevisioni")
    @WebResult(name = "CaricaPrevisioniResult", targetNamespace = "http://m.anm.it/srv/")
    @RequestWrapper(localName = "CaricaPrevisioni", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaPrevisioni")
    @ResponseWrapper(localName = "CaricaPrevisioniResponse", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaPrevisioniResponse")
    public ArrayOfPrevisione caricaPrevisioni(
        @WebParam(name = "Palina", targetNamespace = "http://m.anm.it/srv/")
        String palina);

    /**
     * 
     * @param palina
     * @return
     *     returns anmbaseservices.ArrayOfLinea
     */
    @WebMethod(operationName = "CaricaTransiti", action = "http://m.anm.it/srv/CaricaTransiti")
    @WebResult(name = "CaricaTransitiResult", targetNamespace = "http://m.anm.it/srv/")
    @RequestWrapper(localName = "CaricaTransiti", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaTransiti")
    @ResponseWrapper(localName = "CaricaTransitiResponse", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaTransitiResponse")
    public ArrayOfLinea caricaTransiti(
        @WebParam(name = "Palina", targetNamespace = "http://m.anm.it/srv/")
        String palina);

    /**
     * 
     * @param linea
     * @return
     *     returns anmbaseservices.ArrayOfPercorso
     */
    @WebMethod(operationName = "CaricaPercorsoLinea", action = "http://m.anm.it/srv/CaricaPercorsoLinea")
    @WebResult(name = "CaricaPercorsoLineaResult", targetNamespace = "http://m.anm.it/srv/")
    @RequestWrapper(localName = "CaricaPercorsoLinea", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaPercorsoLinea")
    @ResponseWrapper(localName = "CaricaPercorsoLineaResponse", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaPercorsoLineaResponse")
    public ArrayOfPercorso caricaPercorsoLinea(
        @WebParam(name = "linea", targetNamespace = "http://m.anm.it/srv/")
        String linea);

    /**
     * 
     * @param fermata
     * @return
     *     returns anmbaseservices.ArrayOfPercorso
     */
    @WebMethod(operationName = "RilevaEsistenzaFermata", action = "http://m.anm.it/srv/RilevaEsistenzaFermata")
    @WebResult(name = "RilevaEsistenzaFermataResult", targetNamespace = "http://m.anm.it/srv/")
    @RequestWrapper(localName = "RilevaEsistenzaFermata", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.RilevaEsistenzaFermata")
    @ResponseWrapper(localName = "RilevaEsistenzaFermataResponse", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.RilevaEsistenzaFermataResponse")
    public ArrayOfPercorso rilevaEsistenzaFermata(
        @WebParam(name = "fermata", targetNamespace = "http://m.anm.it/srv/")
        String fermata);

    /**
     * 
     * @param strada
     * @param citta
     * @return
     *     returns anmbaseservices.ArrayOfPercorso
     */
    @WebMethod(operationName = "CaricaFermateStrada", action = "http://m.anm.it/srv/CaricaFermateStrada")
    @WebResult(name = "CaricaFermateStradaResult", targetNamespace = "http://m.anm.it/srv/")
    @RequestWrapper(localName = "CaricaFermateStrada", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaFermateStrada")
    @ResponseWrapper(localName = "CaricaFermateStradaResponse", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.CaricaFermateStradaResponse")
    public ArrayOfPercorso caricaFermateStrada(
        @WebParam(name = "strada", targetNamespace = "http://m.anm.it/srv/")
        String strada,
        @WebParam(name = "citta", targetNamespace = "http://m.anm.it/srv/")
        String citta);

    /**
     * 
     * @param linea
     * @return
     *     returns anmbaseservices.ArrayOfLinea
     */
    @WebMethod(operationName = "RilevaAnomalieLinea", action = "http://m.anm.it/srv/RilevaAnomalieLinea")
    @WebResult(name = "RilevaAnomalieLineaResult", targetNamespace = "http://m.anm.it/srv/")
    @RequestWrapper(localName = "RilevaAnomalieLinea", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.RilevaAnomalieLinea")
    @ResponseWrapper(localName = "RilevaAnomalieLineaResponse", targetNamespace = "http://m.anm.it/srv/", className = "anmbaseservices.RilevaAnomalieLineaResponse")
    public ArrayOfLinea rilevaAnomalieLinea(
        @WebParam(name = "linea", targetNamespace = "http://m.anm.it/srv/")
        String linea);

}
